using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Ihc.Vis;
using Microsoft.Extensions.Time.Testing;

namespace Ihc.Tests.Shared
{
    /// <summary>
    /// The report-oracle harness shared by the two suites that own a format's byte contract —
    /// <c>safe_project_tests</c> the <c>*.txt</c> oracles (default unicode stand-ins), <c>safe_unit_tests</c>
    /// the <c>*.html</c> ones (OpenVisual's SVG provider, so they need the app assembly). Both drive the same
    /// fixture × kind × mode matrix against the same oracle-naming convention, so the matrix, the naming rule,
    /// the pinned clock and the byte assert live here once. Compiled into both suites through a
    /// <c>&lt;Compile Include&gt;</c> link, mirroring the shared fixture copy in <c>tests/TestData.props</c>.
    /// </summary>
    internal static class ReportOracles
    {
        /// <summary>The instant every <c>full-*</c> oracle's generation timestamp is pinned to (S10):
        /// 2026-07-30 12:00, local on every machine.</summary>
        private static readonly DateTimeOffset PinnedInstant = new(2026, 7, 30, 12, 0, 0, TimeSpan.Zero);

        // The report-kind stem each oracle filename carries.
        private static readonly (ReportKind Kind, string Stem)[] Kinds =
        {
            (ReportKind.Functions, "funktionsdokumentation"),
            (ReportKind.Installation, "installationdokumentation"),
            (ReportKind.FunctionBlocks, "functionblockdokumentation"),
        };

        // The fixture projects the oracles were captured from (their .vis stem).
        private static readonly string[] Fixtures =
        {
            "project3-KompleksWired-enduserdoc",
            "project5-Dokumentation",
        };

        /// <summary>The pinned report clock: <see cref="TimeProvider.GetLocalNow"/> answers
        /// <see cref="PinnedInstant"/> on every machine (<c>FakeTimeProvider</c> defaults its local zone to
        /// UTC), which is what makes the <c>full-*</c> oracles reproducible.</summary>
        public static TimeProvider Clock() => new FakeTimeProvider(PinnedInstant);

        /// <summary>
        /// Every fixture × kind × mode case for one output format, as NUnit
        /// <c>(oracle file, fixture project, kind, mode)</c> rows. The oracle filename is fully mechanical —
        /// <c>{std|full}-{fixture}-{kind stem}.{extension}</c> — so the 12 rows per format are generated
        /// rather than retyped, and a missing combination shows up as a missing file, not a missing row.
        /// </summary>
        public static IEnumerable<object[]> Cases(string extension) =>
            from fixture in Fixtures
            from kind in Kinds
            from mode in new[] { ReportMode.Standard, ReportMode.Full }
            select new object[]
            {
                $"{(mode == ReportMode.Full ? "full" : "std")}-{fixture}-{kind.Stem}.{extension}",
                fixture + ".vis",
                kind.Kind,
                mode,
            };

        /// <summary>
        /// Asserts the generated bytes reproduce the oracle exactly, with an RCA-friendly message naming the
        /// first differing line. CRLF→LF normalization is applied to the ORACLE side only (D6/S06: the
        /// generator always emits LF, but git autocrlf may check the oracle out with CRLF).
        /// </summary>
        public static void AssertMatchesOracle(byte[] oracleBytes, byte[] generated, string oracleFile)
        {
            byte[] expected = oracleBytes.Where(b => b != (byte)'\r').ToArray();
            if (expected.AsSpan().SequenceEqual(generated))
            {
                return;
            }
            string[] expectedLines = Encoding.UTF8.GetString(expected).Split('\n');
            string[] actualLines = Encoding.UTF8.GetString(generated).Split('\n');
            int line = 0;
            while (line < expectedLines.Length && line < actualLines.Length && expectedLines[line] == actualLines[line])
            {
                line++;
            }
            string expectedLine = line < expectedLines.Length ? expectedLines[line] : "<missing — generator emitted extra lines>";
            string actualLine = line < actualLines.Length ? actualLines[line] : "<missing — generator emitted too few lines>";
            Assert.Fail(
                $"{oracleFile}: generated bytes differ from the oracle (expected {expected.Length} bytes, got {generated.Length}).\n" +
                $"First difference at line {line + 1}:\n  oracle: \"{expectedLine}\"\n  actual: \"{actualLine}\"");
        }
    }
}
