
using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.Extensions.Configuration;

namespace Ihc.IOExtractor {
    /**
    * Common base class for generators.
    */
    public abstract class GeneratorBase {
        protected readonly string header = "Generated by IHC Project Extractor";
        protected readonly IConfiguration config;
        protected readonly IDictionary<string, string> idStringReplacements;

        public GeneratorBase(IConfiguration appConfig) {
            this.config = appConfig;
            this.idStringReplacements = GetReplacementStrings(config);
        }

        protected string GetIdentifierName(IOMeta meta) {
            StringBuilder sb = new StringBuilder();

            var source = meta.GroupName +"_"+ meta.ProductPosition + "_" + meta.ProductName+"_"+meta.DatalineName;

            foreach(var r in idStringReplacements) {
                source = source.Replace(r.Key, r.Value);
            }

            bool reqUpper = true; // pascalcase
            bool first = true;
            foreach(var c in source) {
                if (!Char.IsLetter(c) && first) {
                    sb.Append("_");
                } 
                
                if (Char.IsNumber(c) || c == '_') {
                    sb.Append(c);
                } else if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')){
                    if (reqUpper) {
                        sb.Append(Char.ToUpper(c));
                    } else {
                        sb.Append(c);
                    }
                    reqUpper = false;
                } else if (Char.IsSeparator(c)) {
                    // sb.Append("_");
                    reqUpper = true;
                } else {
                    // Do nothing
                }

                first = false;
            }

            return sb.ToString();
        }

        protected static IDictionary<string, string> GetReplacementStrings(IConfiguration config)
        {
            Dictionary<string, string> result = new Dictionary<string, string>();
            DoAddReplacements(config, "identifiers:stringReplacements", result);
            DoAddReplacements(config, "identifiers:stringReplacements2", result);
            return result;
        }

        private static void DoAddReplacements(IConfiguration config, string key, Dictionary<string, string> result)
        {
            var section = config.GetSection(key);
            var children = section.GetChildren();
            foreach (var child in children)
            {
                // A child with no value is a nested section rather than a replacement pair, so the
                // table is misconfigured; say which entry rather than replace with nothing.
                result.Add(child.Key, child.Value
                    ?? throw new InvalidOperationException($"Configuration setting '{child.Path}' must be a string to be used as a replacement."));
            }
        }

        /**
        * Generates output for a IHC project.
        * Must be implemented by all concrete generators.
        */
        public abstract String Generate(IhcProjectLoader project);

        /**
        * Returns file extension to use.
        */
        public abstract String FileExtension();

        /**
        * Appends one line per entry, separating them with a comma. The separator belongs to the
        * gap between two entries, not to an entry, which is why the last one does not get one -
        * every output format here is a list literal that a trailing comma would break.
        */
        protected static void AppendCommaSeparatedLines<T>(T[] entries, StringBuilder buf, Action<T, StringBuilder> appendEntry)
        {
            for (int i = 0; i < entries.Length; ++i)
            {
                appendEntry(entries[i], buf);
                if (i < entries.Length - 1)
                {
                    buf.Append(",");
                }
                buf.Append(Environment.NewLine);
            }
        }
    };

    /**
    * Common base class for the generators that emit a header comment and then one named block of
    * constants per IO direction. What differs between them is the block, not the walk, so the walk
    * lives here and each concrete generator supplies only its own block - and, where its language
    * needs one, an enclosing declaration.
    */
    public abstract class ConstantBlockGenerator : GeneratorBase {
        private readonly string extension;
        private readonly string prologue;
        private readonly string epilogue;

        /**
        * @param extension the generated file's extension.
        * @param prologue the declaration the blocks nest in, for a language that needs one; "" for none.
        * @param epilogue closes whatever the prologue opened.
        */
        public ConstantBlockGenerator(IConfiguration config, string extension, string prologue = "", string epilogue = "")
                : base(config) {
            this.extension = extension;
            this.prologue = prologue;
            this.epilogue = epilogue;
        }

        public override String Generate(IhcProjectLoader project)
        {
            StringBuilder buf = new StringBuilder();

            buf.AppendFormat("// {0}" + Environment.NewLine, header);

            buf.Append(prologue);
            AppendIoBlock(project.GetIO(IOType.Input), "Inputs", buf);
            AppendIoBlock(project.GetIO(IOType.Output), "Outputs", buf);
            buf.Append(epilogue);

            return buf.ToString();
        }

        public override String FileExtension() {
            return extension;
        }

        /**
        * Emits one named block holding a constant per IO entry.
        */
        protected abstract void AppendIoBlock(IOMeta[] ioAry, string blockName, StringBuilder buf);
    };

    /**
    * Generator for the script languages, whose blocks differ only in how the block and its members are
    * spelled. The spellings are constructor arguments rather than overridden methods, so this class is
    * CONCRETE: a dialect is an instantiation, not a subclass, and Program.cs shows what each one emits
    * without a reader having to resolve two constructors through two base classes.
    */
    public class ScriptConstantGenerator : ConstantBlockGenerator {
        private readonly string blockOpenFormat;
        private readonly string memberFormat;
        private readonly string blockClose;

        /**
        * @param blockOpenFormat opens the block; {0} is the block name.
        * @param memberFormat one member; {0} is its identifier and {1} its hex resource id.
        * @param blockClose closes the block. Passed alongside the open so a dialect's whole block shape
        *        sits at one call site rather than half here and half in the base.
        */
        public ScriptConstantGenerator(IConfiguration config, string extension,
                                       string blockOpenFormat, string memberFormat, string blockClose)
                : base(config, extension) {
            this.blockOpenFormat = blockOpenFormat;
            this.memberFormat = memberFormat;
            this.blockClose = blockClose;
        }

        protected override void AppendIoBlock(IOMeta[] ioAry, string blockName, StringBuilder buf)
        {
            buf.AppendFormat(blockOpenFormat + Environment.NewLine, blockName);

            AppendCommaSeparatedLines(ioAry, buf, (io, b) =>
                b.AppendFormat(memberFormat, GetIdentifierName(io), io.ResourceId.ToString("X8")));

            buf.Append(blockClose + Environment.NewLine + Environment.NewLine);
        }
    };

    /**
    * Generator for json (outputs everything for diagnostics)
    */
    public class JsonGenerator : GeneratorBase {
        public JsonGenerator(IConfiguration config) : base(config) {
        }

        public override String Generate(IhcProjectLoader project)
        {
            var inputs = project.GetIO(IOType.Input);
            var outputs = project.GetIO(IOType.Output);

            StringBuilder buf = new StringBuilder();

            buf.Append("{" + Environment.NewLine);
            buf.AppendFormat(" \"comment\": \"{0}\"," + Environment.NewLine, header);

            buf.Append(" \"Inputs\": [" + Environment.NewLine);
            GenerateIoList(inputs, buf);
            buf.Append(" ]," + Environment.NewLine);

            buf.Append(" \"Outputs\": [" + Environment.NewLine);
            GenerateIoList(outputs, buf);
            buf.Append(" ]");
            buf.Append("}" + Environment.NewLine);

            return buf.ToString();
        }

        private void GenerateIoList(IOMeta[] ioAry, StringBuilder buf)
        {
            AppendCommaSeparatedLines(ioAry, buf, (io, b) =>
            {
                b.Append("  {");
                b.AppendFormat("\" GroupId\" : {0}, ", io.GroupId);
                b.AppendFormat("\"ResourceId\" : {0}, ", io.ResourceId);
                b.AppendFormat("\"ProductId\" : {0}, ", io.ProductId);
                b.AppendFormat("\"GroupName\" : \"{0}\", ", io.GroupName.Replace("\"", "\\\""));
                b.AppendFormat("\"DatalineName\" : \"{0}\", ", io.DatalineName.Replace("\"", "\\\""));
                b.AppendFormat("\"ProductName\" : \"{0}\", ", io.ProductName.Replace("\"", "\\\""));
                b.AppendFormat("\"ProductPosition\" : \"{0}\", ", io.ProductPosition.Replace("\"", "\\\""));
                b.AppendFormat("\"ProductNote\" : \"{0}\", ", io.ProductNote.Replace("\"", "\\\""));
                b.AppendFormat("\"DatalineNameNote\" : \"{0}\", ", io.DatalineNote.Replace("\"", "\\\""));
                b.AppendFormat("\"IdentifierName\" : \"{0}\" ", GetIdentifierName(io));
                b.Append(" }");
            });
        }

        public override String FileExtension() {
            return "json";
        }
    };

    /**
    * C# generator for input/output constants.
    */
    public class CSharpGenerator : ConstantBlockGenerator {
        public CSharpGenerator(IConfiguration config)
                : base(config, "cs", Prologue(config), "}" + Environment.NewLine) {
        }

        private static string Prologue(IConfiguration config)
        {
            return "namespace " + config.GetSection("CSharpGenerator")["namespace"] + " {" + Environment.NewLine;
        }

        // A class member per line, terminated rather than separated, so this one does not go through
        // AppendCommaSeparatedLines.
        protected override void AppendIoBlock(IOMeta[] ioAry, string blockName, StringBuilder buf)
        {
            buf.Append("  public sealed class " + blockName + " { " + Environment.NewLine);

            foreach (var io in ioAry)
            {
                buf.AppendFormat("    public const int {0} = 0x{1};" + Environment.NewLine, GetIdentifierName(io), io.ResourceId.ToString("X8"));
            }

            buf.Append("  }" + Environment.NewLine);
        }
    };
}