<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <CopyIhcSettingsToOutput>true</CopyIhcSettingsToOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json"/>
  </ItemGroup>
</Project>