#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

using Ihc.Vis.Catalog;
using Ihc.Vis.FunctionBlocks;

namespace Ihc.Vis.CatalogCodegen
{
    /// <summary>
    /// Emits the committed <c>BuiltInCatalog.FunctionBlocks.g.cs</c> from the vendor function-block catalog. Each
    /// <c>.ifb</c> is decompiled to a <see cref="FunctionBlockRecipe"/> (with its <c>syn_en*.md</c> documentation
    /// attached) and self-verified (<see cref="FbSelfVerify"/>) BEFORE anything is written; if any block fails, nothing
    /// is emitted. Blocks are ordered exactly as <c>CatalogDiscovery</c> scans them (path-sorted, ordinal), so the
    /// generated registration reproduces the install-dir last-wins semantics over the four favorites that duplicate a
    /// <c>master_type</c> (<c>00. Foretrukne</c> sorts first, so the real-category copy registers later and wins).
    /// </summary>
    internal static class FunctionBlockCatalogEmitter
    {
        public const string FileName = "BuiltInCatalog.FunctionBlocks.g.cs";

        public static EmitReport Emit(string functionBlocksDir, string outDir)
        {
            IReadOnlyList<string> files = Directory
                .EnumerateFiles(functionBlocksDir, "*.ifb", SearchOption.AllDirectories)
                .OrderBy(p => p, StringComparer.Ordinal)
                .ToArray();

            var factories = new List<(string Method, FunctionBlockRecipe Recipe)>();
            var usedNames = new Dictionary<string, int>(StringComparer.Ordinal);
            var failures = new List<string>();

            foreach (string path in files)
            {
                string name = Path.GetFileName(path);
                string categoryPath = Path.GetDirectoryName(Path.GetRelativePath(functionBlocksDir, path)) ?? string.Empty;
                FunctionBlockSource source = CatalogSourceFile.ReadFunctionBlock(path, categoryPath);
                FunctionBlockDocumentation? documentation = FunctionBlockDocReader.ForFunctionBlock(path, synEnOnly: true);
                FunctionBlockRecipe recipe;
                try
                {
                    recipe = FunctionBlockDecompiler.Decompile(source.Definition, source.Blocks, documentation);
                }
                catch (DecompileNotSupportedException ex)
                {
                    failures.Add($"{name}: UNSUPPORTED — {ex.Message}");
                    continue;
                }

                VerifyResult result = FbSelfVerify.Verify(recipe, source);
                if (!result.Ok)
                {
                    failures.Add($"{name}: FAIL — {result.Reason}");
                    continue;
                }
                factories.Add((UniqueMethodName(usedNames, source.Definition.MasterType), recipe));
            }

            if (failures.Count > 0)
            {
                return new EmitReport(files.Count, factories.Count, failures, Written: false, OutputPath: null);
            }

            Directory.CreateDirectory(outDir);
            string outputPath = Path.Combine(outDir, FileName);
            File.WriteAllText(outputPath, RenderFile(factories), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            return new EmitReport(files.Count, factories.Count, failures, Written: true, OutputPath: outputPath);
        }

        private static string UniqueMethodName(Dictionary<string, int> used, string masterType)
        {
            var sanitized = new StringBuilder("FunctionBlock_");
            foreach (char c in masterType)
            {
                sanitized.Append(char.IsLetterOrDigit(c) ? c : '_');
            }
            string baseName = sanitized.ToString();
            if (!used.TryGetValue(baseName, out int count))
            {
                used[baseName] = 1;
                return baseName;
            }
            used[baseName] = ++count;
            return $"{baseName}_{count}";
        }

        private static string RenderFile(IReadOnlyList<(string Method, FunctionBlockRecipe Recipe)> factories)
        {
            var builder = new StringBuilder();
            builder.Append(
                "// <auto-generated>\n" +
                "//     Generated by utilities/ihc_catalog_codegen from the IHC Visual function-block catalog (FunctionBlocks\\*.ifb).\n" +
                "//     Do NOT edit by hand — re-run the generator to regenerate. See tmp/catalogplan-functionblocks.md.\n" +
                "// </auto-generated>\n" +
                "#nullable enable\n" +
                "using System;\n" +
                "using System.Collections.Immutable;\n" +
                "\n" +
                "using Ihc.Vis.FunctionBlocks;\n" +
                "\n" +
                "namespace Ihc.Vis.Catalog\n" +
                "{\n" +
                "    public sealed partial class BuiltInCatalog\n" +
                "    {\n" +
                "        // Registers every code-authored function block, in the same document order catalog discovery scans\n" +
                "        // the install dir, so last-wins lookup over the four master_type-duplicating favorites matches it.\n" +
                "        partial void RegisterFunctionBlocks(ImmutableArray<FunctionBlockDefinition>.Builder functionBlocks)\n" +
                "        {\n");
            foreach ((string method, _) in factories)
            {
                builder.Append("            functionBlocks.Add(").Append(method).Append("());\n");
            }
            builder.Append("        }\n\n");

            foreach ((string method, FunctionBlockRecipe recipe) in factories)
            {
                builder.Append(recipe.RenderMethod(method)).Append('\n');
            }

            builder.Append(
                "    }\n" +
                "}\n");
            return builder.ToString();
        }
    }
}
