#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

using Ihc.Vis.Catalog;

namespace Ihc.Vis.CatalogCodegen
{
    /// <summary>Outcome of one catalog decompile sweep (products or function blocks): every source decompiled to a
    /// self-verified recipe, or the per-file failures that must abort the whole emit (nothing is ever published
    /// unless every component of BOTH sweeps verified). The file names ride along for grammar-table doc comments.</summary>
    internal sealed record DecompileReport<TRecipe>(int Scanned,
        IReadOnlyList<(string File, string Method, TRecipe Recipe)> Factories, IReadOnlyList<string> Failures);

    /// <summary>
    /// Renders the committed <c>BuiltInCatalog.Products.g.cs</c> from the vendor product catalog. Each <c>.def</c>
    /// is decompiled to a <see cref="ProductRecipe"/> and self-verified (<see cref="SelfVerify"/>); the coordinated
    /// publish pipeline in <c>Program.RunEmit</c> renders and writes all three generated files only when every
    /// component of both sweeps verified. Products are ordered exactly as <c>CatalogDiscovery</c> scans them
    /// (path-sorted, ordinal), so the generated registration reproduces the install-dir last-wins semantics over
    /// duplicate <c>product_identifier</c>s; method names are disambiguated for those duplicates. The output is
    /// deterministic — a re-run over an unchanged corpus produces a byte-identical file.
    /// </summary>
    internal static class ProductCatalogEmitter
    {
        public const string FileName = "BuiltInCatalog.Products.g.cs";

        public static DecompileReport<ProductRecipe> Decompile(string productsDir)
        {
            IReadOnlyList<string> files = Directory
                .EnumerateFiles(productsDir, "*.def", SearchOption.AllDirectories)
                .OrderBy(p => p, StringComparer.Ordinal)
                .ToArray();

            var factories = new List<(string File, string Method, ProductRecipe Recipe)>();
            var usedNames = new Dictionary<string, int>(StringComparer.Ordinal);
            var failures = new List<string>();

            foreach (string path in files)
            {
                string name = Path.GetFileName(path);
                string categoryPath = Path.GetDirectoryName(Path.GetRelativePath(productsDir, path)) ?? string.Empty;
                ProductSource source = CatalogSourceFile.ReadProduct(path, categoryPath);
                ProductRecipe recipe;
                try
                {
                    recipe = ProductDecompiler.Decompile(
                        source.Definition.Body, source.Blocks, source.Definition.DisplayName, categoryPath);
                    recipe.BakeSourceFidelity(source);   // strict grammar parse — throws on an out-of-envelope header
                }
                catch (Exception ex) when (ex is DecompileNotSupportedException or CatalogFormatException)
                {
                    failures.Add($"{name}: UNSUPPORTED — {ex.Message}");
                    continue;
                }

                VerifyResult result = SelfVerify.Verify(recipe, source);
                if (!result.Ok)
                {
                    failures.Add($"{name}: FAIL — {result.Reason}");
                    continue;
                }
                factories.Add((name, UniqueMethodName(usedNames, source.Definition.ProductIdentifier), recipe));
            }
            return new DecompileReport<ProductRecipe>(files.Count, factories, failures);
        }

        private static string UniqueMethodName(Dictionary<string, int> used, string productIdentifier)
        {
            var sanitized = new StringBuilder("Product");
            foreach (char c in productIdentifier)
            {
                sanitized.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            }
            string baseName = sanitized.ToString();
            if (!used.TryGetValue(baseName, out int count))
            {
                used[baseName] = 1;
                return baseName;
            }
            used[baseName] = ++count;
            return $"{baseName}_{count}";
        }

        public static string RenderFile(IReadOnlyList<(string File, string Method, ProductRecipe Recipe)> factories,
            GrammarTable grammars)
        {
            var builder = new StringBuilder();
            builder.Append(
                "// <auto-generated>\n" +
                "//     Generated by utilities/ihc_catalog_codegen from the IHC Visual product catalog (Products\\*.def).\n" +
                "//     Do NOT edit by hand — re-run the generator to regenerate. See tmp/catalogdtd-plan.md.\n" +
                "// </auto-generated>\n" +
                "#nullable enable\n" +
                "using System.Collections.Immutable;\n" +
                "\n" +
                "using Ihc.Vis.Model;\n" +
                "using Ihc.Vis.Products;\n" +
                "\n" +
                "namespace Ihc.Vis.Catalog\n" +
                "{\n" +
                "    public sealed partial class BuiltInCatalog\n" +
                "    {\n" +
                "        // Registers every code-authored product, in the same document order catalog discovery scans the\n" +
                "        // install dir, so last-wins lookup over duplicate product_identifiers matches the install-dir path.\n" +
                "        partial void RegisterProducts(ImmutableArray<ProductDefinition>.Builder products)\n" +
                "        {\n");
            foreach ((_, string method, _) in factories)
            {
                builder.Append("            products.Add(").Append(method).Append("());\n");
            }
            builder.Append("        }\n\n");

            foreach ((_, string method, ProductRecipe recipe) in factories)
            {
                builder.Append(recipe.RenderMethod(method, grammars.RefFor(recipe.SourceGrammar))).Append('\n');
            }

            builder.Append(
                "        // Builds a catalog subtree element from its verbatim attributes (id included at its file position, so\n" +
                "        // a vendor element that writes id after another attribute round-trips byte-faithfully). The id token\n" +
                "        // parses the ElementId; placeholder ids are re-minted in place by the insert transform / id stamping.\n" +
                "        private static ProjectElement ElRaw(string tag, (string, string)[] attrs, params ProjectElement[] children)\n" +
                "        {\n" +
                "            string? idToken = null;\n" +
                "            foreach ((string name, string value) in attrs)\n" +
                "            {\n" +
                "                if (name == \"id\") { idToken = value; break; }\n" +
                "            }\n" +
                "            ElementId? id = idToken is not null && ElementId.TryParse(idToken, out ElementId parsed) ? parsed : null;\n" +
                "            return new ProjectElement(tag, id, attrs.ToImmutableArray(), children.ToImmutableArray());\n" +
                "        }\n" +
                "    }\n" +
                "}\n");
            return builder.ToString();
        }
    }
}
