#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Ihc.Vis.CatalogCodegen
{
    /// <summary>Outcome of a catalog emit: how many products were scanned/emitted, any per-file failures, and whether a
    /// file was actually written (nothing is written unless every product self-verified).</summary>
    internal sealed record EmitReport(int Scanned, int Emitted, IReadOnlyList<string> Failures, bool Written,
        string? OutputPath);

    /// <summary>
    /// Emits the committed <c>BuiltInCatalog.Products.g.cs</c> from the vendor product catalog. Each <c>.def</c> is
    /// decompiled to a <see cref="ProductRecipe"/> and self-verified (<see cref="SelfVerify"/>) BEFORE anything is
    /// written; if any product fails, nothing is emitted (the Decision Framework's "never commit a failing .g.cs").
    /// Products are ordered exactly as <c>CatalogDiscovery</c> scans them (path-sorted, ordinal), so the generated
    /// registration reproduces the install-dir last-wins semantics over duplicate <c>product_identifier</c>s; method
    /// names are disambiguated for those duplicates. The output is deterministic — a re-run over an unchanged corpus
    /// produces a byte-identical file.
    /// </summary>
    internal static class ProductCatalogEmitter
    {
        public const string FileName = "BuiltInCatalog.Products.g.cs";

        public static EmitReport Emit(string productsDir, string outDir)
        {
            IReadOnlyList<string> files = Directory
                .EnumerateFiles(productsDir, "*.def", SearchOption.AllDirectories)
                .OrderBy(p => p, StringComparer.Ordinal)
                .ToArray();

            var factories = new List<(string Method, ProductRecipe Recipe)>();
            var usedNames = new Dictionary<string, int>(StringComparer.Ordinal);
            var failures = new List<string>();

            foreach (string path in files)
            {
                string name = Path.GetFileName(path);
                string categoryPath = Path.GetDirectoryName(Path.GetRelativePath(productsDir, path)) ?? string.Empty;
                ProductSource source = CatalogSourceFile.ReadProduct(path, categoryPath);
                ProductRecipe recipe;
                try
                {
                    recipe = ProductDecompiler.Decompile(
                        source.Definition.Body, source.Blocks, source.Definition.DisplayName, categoryPath);
                }
                catch (DecompileNotSupportedException ex)
                {
                    failures.Add($"{name}: UNSUPPORTED — {ex.Message}");
                    continue;
                }

                VerifyResult result = SelfVerify.Verify(recipe, source);
                if (!result.Ok)
                {
                    failures.Add($"{name}: FAIL — {result.Reason}");
                    continue;
                }
                factories.Add((UniqueMethodName(usedNames, source.Definition.ProductIdentifier), recipe));
            }

            if (failures.Count > 0)
            {
                return new EmitReport(files.Count, factories.Count, failures, Written: false, OutputPath: null);
            }

            Directory.CreateDirectory(outDir);
            string outputPath = Path.Combine(outDir, FileName);
            // UTF-8 without BOM, matching the repo's hand-authored .cs (Danish characters ride along as literal UTF-8).
            File.WriteAllText(outputPath, RenderFile(factories), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            return new EmitReport(files.Count, factories.Count, failures, Written: true, OutputPath: outputPath);
        }

        private static string UniqueMethodName(Dictionary<string, int> used, string productIdentifier)
        {
            var sanitized = new StringBuilder("Product");
            foreach (char c in productIdentifier)
            {
                sanitized.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            }
            string baseName = sanitized.ToString();
            if (!used.TryGetValue(baseName, out int count))
            {
                used[baseName] = 1;
                return baseName;
            }
            used[baseName] = ++count;
            return $"{baseName}_{count}";
        }

        private static string RenderFile(IReadOnlyList<(string Method, ProductRecipe Recipe)> factories)
        {
            var builder = new StringBuilder();
            builder.Append(
                "// <auto-generated>\n" +
                "//     Generated by utilities/ihc_catalog_codegen from the IHC Visual product catalog (Products\\*.def).\n" +
                "//     Do NOT edit by hand — re-run the generator to regenerate. See tmp/catalogplan-products.md.\n" +
                "// </auto-generated>\n" +
                "#nullable enable\n" +
                "using System.Collections.Immutable;\n" +
                "\n" +
                "using Ihc.Vis.Model;\n" +
                "using Ihc.Vis.Products;\n" +
                "\n" +
                "namespace Ihc.Vis.Catalog\n" +
                "{\n" +
                "    public sealed partial class BuiltInCatalog\n" +
                "    {\n" +
                "        // Registers every code-authored product, in the same document order catalog discovery scans the\n" +
                "        // install dir, so last-wins lookup over duplicate product_identifiers matches the install-dir path.\n" +
                "        partial void RegisterProducts(ImmutableArray<ProductDefinition>.Builder products)\n" +
                "        {\n");
            foreach ((string method, _) in factories)
            {
                builder.Append("            products.Add(").Append(method).Append("());\n");
            }
            builder.Append("        }\n\n");

            foreach ((string method, ProductRecipe recipe) in factories)
            {
                builder.Append(recipe.RenderMethod(method)).Append('\n');
            }

            builder.Append(
                "        // Builds a catalog subtree element carrying its source id token verbatim, so an IDREF inside the\n" +
                "        // subtree still names its target. These placeholder ids are re-minted by the insert transform; only\n" +
                "        // their internal consistency matters. Mirrors the ElRaw helper the product oracle tests use.\n" +
                "        private static ProjectElement ElRaw(string tag, string idToken, (string, string)[] attrs,\n" +
                "            params ProjectElement[] children)\n" +
                "        {\n" +
                "            ElementId? id = ElementId.TryParse(idToken, out ElementId parsed) ? parsed : null;\n" +
                "            ImmutableArray<(string, string)>.Builder bag =\n" +
                "                ImmutableArray.CreateBuilder<(string, string)>(attrs.Length + 1);\n" +
                "            bag.Add((\"id\", idToken));\n" +
                "            bag.AddRange(attrs);\n" +
                "            return new ProjectElement(tag, id, bag.ToImmutable(), children.ToImmutableArray());\n" +
                "        }\n" +
                "    }\n" +
                "}\n");
            return builder.ToString();
        }
    }
}
