<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="CompareNETObjects" />
    <PackageReference Include="CsCheck" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Headless.NUnit" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
    <ProjectReference Include="..\..\ihcclient\ihcclient.csproj" />
    <ProjectReference Include="..\..\utilities\ihc_lab\ihc_lab.csproj" />
  </ItemGroup>
</Project>
