//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ihc.Soap.Leddimmermanagement
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="utcs", ConfigurationName="Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService")]
    public interface LEDDimmerManagementService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="enterConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName1> enterConfigurationAsync(Ihc.Soap.Leddimmermanagement.inputMessageName1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="exitConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName2> exitConfigurationAsync(Ihc.Soap.Leddimmermanagement.inputMessageName2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="waitForDeviceDetected", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName3> waitForDeviceDetectedAsync(Ihc.Soap.Leddimmermanagement.inputMessageName3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="scanConfiguredDevices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName4> scanConfiguredDevicesAsync(Ihc.Soap.Leddimmermanagement.inputMessageName4 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="assignID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName5> assignIDAsync(Ihc.Soap.Leddimmermanagement.inputMessageName5 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getDeviceCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName6> getDeviceCountAsync(Ihc.Soap.Leddimmermanagement.inputMessageName6 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getLightLevel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName7> getLightLevelAsync(Ihc.Soap.Leddimmermanagement.inputMessageName7 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getDeviceList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName8> getDeviceListAsync(Ihc.Soap.Leddimmermanagement.inputMessageName8 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="startFirmwareUpgrade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName9> startFirmwareUpgradeAsync(Ihc.Soap.Leddimmermanagement.inputMessageName9 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getFirmwareUpgradeProgress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName10> getFirmwareUpgradeProgressAsync(Ihc.Soap.Leddimmermanagement.inputMessageName10 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName1
    {
        
        public inputMessageName1()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> enterConfiguration1;
        
        public outputMessageName1()
        {
        }
        
        public outputMessageName1(System.Nullable<bool> enterConfiguration1)
        {
            this.enterConfiguration1 = enterConfiguration1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName2
    {
        
        public inputMessageName2()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName2
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> exitConfiguration1;
        
        public outputMessageName2()
        {
        }
        
        public outputMessageName2(System.Nullable<bool> exitConfiguration1)
        {
            this.exitConfiguration1 = exitConfiguration1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSLEDDimmerInfo
    {
        
        private string locationField;
        
        private sbyte channelField;
        
        private string bootloaderVersionField;
        
        private string applicationVersionField;
        
        private sbyte applicationStatusField;
        
        private string hardwareVersionField;
        
        private string serialNumberField;
        
        private sbyte levelField;
        
        private sbyte errorFlagsField;
        
        private sbyte channelIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public sbyte channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string bootloaderVersion
        {
            get
            {
                return this.bootloaderVersionField;
            }
            set
            {
                this.bootloaderVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string applicationVersion
        {
            get
            {
                return this.applicationVersionField;
            }
            set
            {
                this.applicationVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public sbyte applicationStatus
        {
            get
            {
                return this.applicationStatusField;
            }
            set
            {
                this.applicationStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string hardwareVersion
        {
            get
            {
                return this.hardwareVersionField;
            }
            set
            {
                this.hardwareVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string serialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public sbyte level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public sbyte errorFlags
        {
            get
            {
                return this.errorFlagsField;
            }
            set
            {
                this.errorFlagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public sbyte channelID
        {
            get
            {
                return this.channelIDField;
            }
            set
            {
                this.channelIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSLEDDimmerProgress
    {
        
        private string messageField;
        
        private string serialNumberField;
        
        private string statusField;
        
        private int progressField;
        
        private int maximumField;
        
        private string rUNNINGField;
        
        private string fINISHEDField;
        
        private string fAILEDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int progress
        {
            get
            {
                return this.progressField;
            }
            set
            {
                this.progressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int maximum
        {
            get
            {
                return this.maximumField;
            }
            set
            {
                this.maximumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RUNNING
        {
            get
            {
                return this.rUNNINGField;
            }
            set
            {
                this.rUNNINGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FINISHED
        {
            get
            {
                return this.fINISHEDField;
            }
            set
            {
                this.fINISHEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FAILED
        {
            get
            {
                return this.fAILEDField;
            }
            set
            {
                this.fAILEDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSLEDDimmerLevel
    {
        
        private sbyte levelField;
        
        private sbyte errorFlagsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public sbyte level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public sbyte errorFlags
        {
            get
            {
                return this.errorFlagsField;
            }
            set
            {
                this.errorFlagsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> waitForDeviceDetected1;
        
        public inputMessageName3()
        {
        }
        
        public inputMessageName3(System.Nullable<int> waitForDeviceDetected1)
        {
            this.waitForDeviceDetected1 = waitForDeviceDetected1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Leddimmermanagement.WSLEDDimmerInfo waitForDeviceDetected2;
        
        public outputMessageName3()
        {
        }
        
        public outputMessageName3(Ihc.Soap.Leddimmermanagement.WSLEDDimmerInfo waitForDeviceDetected2)
        {
            this.waitForDeviceDetected2 = waitForDeviceDetected2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName4
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> scanConfiguredDevices1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> scanConfiguredDevices2;
        
        public inputMessageName4()
        {
        }
        
        public inputMessageName4(System.Nullable<int> scanConfiguredDevices1, System.Nullable<int> scanConfiguredDevices2)
        {
            this.scanConfiguredDevices1 = scanConfiguredDevices1;
            this.scanConfiguredDevices2 = scanConfiguredDevices2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName4
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Leddimmermanagement.WSLEDDimmerInfo[] scanConfiguredDevices3;
        
        public outputMessageName4()
        {
        }
        
        public outputMessageName4(Ihc.Soap.Leddimmermanagement.WSLEDDimmerInfo[] scanConfiguredDevices3)
        {
            this.scanConfiguredDevices3 = scanConfiguredDevices3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName5
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string assignID1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<sbyte> assignID2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<sbyte> assignID3;
        
        public inputMessageName5()
        {
        }
        
        public inputMessageName5(string assignID1, System.Nullable<sbyte> assignID2, System.Nullable<sbyte> assignID3)
        {
            this.assignID1 = assignID1;
            this.assignID2 = assignID2;
            this.assignID3 = assignID3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName5
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> assignID4;
        
        public outputMessageName5()
        {
        }
        
        public outputMessageName5(System.Nullable<bool> assignID4)
        {
            this.assignID4 = assignID4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName6
    {
        
        public inputMessageName6()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName6
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getDeviceCount1;
        
        public outputMessageName6()
        {
        }
        
        public outputMessageName6(System.Nullable<int> getDeviceCount1)
        {
            this.getDeviceCount1 = getDeviceCount1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName7
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<sbyte> getLightLevel1;
        
        public inputMessageName7()
        {
        }
        
        public inputMessageName7(System.Nullable<sbyte> getLightLevel1)
        {
            this.getLightLevel1 = getLightLevel1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName7
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Leddimmermanagement.WSLEDDimmerLevel getLightLevel2;
        
        public outputMessageName7()
        {
        }
        
        public outputMessageName7(Ihc.Soap.Leddimmermanagement.WSLEDDimmerLevel getLightLevel2)
        {
            this.getLightLevel2 = getLightLevel2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName8
    {
        
        public inputMessageName8()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName8
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Leddimmermanagement.WSLEDDimmerInfo[] getDeviceList1;
        
        public outputMessageName8()
        {
        }
        
        public outputMessageName8(Ihc.Soap.Leddimmermanagement.WSLEDDimmerInfo[] getDeviceList1)
        {
            this.getDeviceList1 = getDeviceList1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName9
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string startFirmwareUpgrade1;
        
        public inputMessageName9()
        {
        }
        
        public inputMessageName9(string startFirmwareUpgrade1)
        {
            this.startFirmwareUpgrade1 = startFirmwareUpgrade1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName9
    {
        
        public outputMessageName9()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName10
    {
        
        public inputMessageName10()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName10
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Leddimmermanagement.WSLEDDimmerProgress getFirmwareUpgradeProgress1;
        
        public outputMessageName10()
        {
        }
        
        public outputMessageName10(Ihc.Soap.Leddimmermanagement.WSLEDDimmerProgress getFirmwareUpgradeProgress1)
        {
            this.getFirmwareUpgradeProgress1 = getFirmwareUpgradeProgress1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface LEDDimmerManagementServiceChannel : Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class LEDDimmerManagementServiceClient : System.ServiceModel.ClientBase<Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService>, Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LEDDimmerManagementServiceClient() : 
                base(LEDDimmerManagementServiceClient.GetDefaultBinding(), LEDDimmerManagementServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.LEDDimmerManagementServiceBindingPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LEDDimmerManagementServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LEDDimmerManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), LEDDimmerManagementServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LEDDimmerManagementServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LEDDimmerManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LEDDimmerManagementServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LEDDimmerManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LEDDimmerManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName1> Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService.enterConfigurationAsync(Ihc.Soap.Leddimmermanagement.inputMessageName1 request)
        {
            return base.Channel.enterConfigurationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName1> enterConfigurationAsync()
        {
            Ihc.Soap.Leddimmermanagement.inputMessageName1 inValue = new Ihc.Soap.Leddimmermanagement.inputMessageName1();
            return ((Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService)(this)).enterConfigurationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName2> Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService.exitConfigurationAsync(Ihc.Soap.Leddimmermanagement.inputMessageName2 request)
        {
            return base.Channel.exitConfigurationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName2> exitConfigurationAsync()
        {
            Ihc.Soap.Leddimmermanagement.inputMessageName2 inValue = new Ihc.Soap.Leddimmermanagement.inputMessageName2();
            return ((Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService)(this)).exitConfigurationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName3> Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService.waitForDeviceDetectedAsync(Ihc.Soap.Leddimmermanagement.inputMessageName3 request)
        {
            return base.Channel.waitForDeviceDetectedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName3> waitForDeviceDetectedAsync(System.Nullable<int> waitForDeviceDetected1)
        {
            Ihc.Soap.Leddimmermanagement.inputMessageName3 inValue = new Ihc.Soap.Leddimmermanagement.inputMessageName3();
            inValue.waitForDeviceDetected1 = waitForDeviceDetected1;
            return ((Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService)(this)).waitForDeviceDetectedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName4> Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService.scanConfiguredDevicesAsync(Ihc.Soap.Leddimmermanagement.inputMessageName4 request)
        {
            return base.Channel.scanConfiguredDevicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName4> scanConfiguredDevicesAsync(System.Nullable<int> scanConfiguredDevices1, System.Nullable<int> scanConfiguredDevices2)
        {
            Ihc.Soap.Leddimmermanagement.inputMessageName4 inValue = new Ihc.Soap.Leddimmermanagement.inputMessageName4();
            inValue.scanConfiguredDevices1 = scanConfiguredDevices1;
            inValue.scanConfiguredDevices2 = scanConfiguredDevices2;
            return ((Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService)(this)).scanConfiguredDevicesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName5> Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService.assignIDAsync(Ihc.Soap.Leddimmermanagement.inputMessageName5 request)
        {
            return base.Channel.assignIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName5> assignIDAsync(string assignID1, System.Nullable<sbyte> assignID2, System.Nullable<sbyte> assignID3)
        {
            Ihc.Soap.Leddimmermanagement.inputMessageName5 inValue = new Ihc.Soap.Leddimmermanagement.inputMessageName5();
            inValue.assignID1 = assignID1;
            inValue.assignID2 = assignID2;
            inValue.assignID3 = assignID3;
            return ((Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService)(this)).assignIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName6> Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService.getDeviceCountAsync(Ihc.Soap.Leddimmermanagement.inputMessageName6 request)
        {
            return base.Channel.getDeviceCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName6> getDeviceCountAsync()
        {
            Ihc.Soap.Leddimmermanagement.inputMessageName6 inValue = new Ihc.Soap.Leddimmermanagement.inputMessageName6();
            return ((Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService)(this)).getDeviceCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName7> Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService.getLightLevelAsync(Ihc.Soap.Leddimmermanagement.inputMessageName7 request)
        {
            return base.Channel.getLightLevelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName7> getLightLevelAsync(System.Nullable<sbyte> getLightLevel1)
        {
            Ihc.Soap.Leddimmermanagement.inputMessageName7 inValue = new Ihc.Soap.Leddimmermanagement.inputMessageName7();
            inValue.getLightLevel1 = getLightLevel1;
            return ((Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService)(this)).getLightLevelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName8> Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService.getDeviceListAsync(Ihc.Soap.Leddimmermanagement.inputMessageName8 request)
        {
            return base.Channel.getDeviceListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName8> getDeviceListAsync()
        {
            Ihc.Soap.Leddimmermanagement.inputMessageName8 inValue = new Ihc.Soap.Leddimmermanagement.inputMessageName8();
            return ((Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService)(this)).getDeviceListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName9> Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService.startFirmwareUpgradeAsync(Ihc.Soap.Leddimmermanagement.inputMessageName9 request)
        {
            return base.Channel.startFirmwareUpgradeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName9> startFirmwareUpgradeAsync(string startFirmwareUpgrade1)
        {
            Ihc.Soap.Leddimmermanagement.inputMessageName9 inValue = new Ihc.Soap.Leddimmermanagement.inputMessageName9();
            inValue.startFirmwareUpgrade1 = startFirmwareUpgrade1;
            return ((Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService)(this)).startFirmwareUpgradeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName10> Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService.getFirmwareUpgradeProgressAsync(Ihc.Soap.Leddimmermanagement.inputMessageName10 request)
        {
            return base.Channel.getFirmwareUpgradeProgressAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Leddimmermanagement.outputMessageName10> getFirmwareUpgradeProgressAsync()
        {
            Ihc.Soap.Leddimmermanagement.inputMessageName10 inValue = new Ihc.Soap.Leddimmermanagement.inputMessageName10();
            return ((Ihc.Soap.Leddimmermanagement.LEDDimmerManagementService)(this)).getFirmwareUpgradeProgressAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LEDDimmerManagementServiceBindingPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LEDDimmerManagementServiceBindingPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/LEDDimmerManagementService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LEDDimmerManagementServiceClient.GetBindingForEndpoint(EndpointConfiguration.LEDDimmerManagementServiceBindingPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LEDDimmerManagementServiceClient.GetEndpointAddress(EndpointConfiguration.LEDDimmerManagementServiceBindingPort);
        }
        
        public enum EndpointConfiguration
        {
            
            LEDDimmerManagementServiceBindingPort,
        }
    }
}
