//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ihc.Soap.Smsmodem
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="utcs", ConfigurationName="Ihc.Soap.Smsmodem.SMSModemService")]
    public interface SMSModemService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="setSMSModemSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName1> setSMSModemSettingsAsync(Ihc.Soap.Smsmodem.inputMessageName1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSMSModemSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName2> getSMSModemSettingsAsync(Ihc.Soap.Smsmodem.inputMessageName2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSMSModemStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName3> getSMSModemStatusAsync(Ihc.Soap.Smsmodem.inputMessageName3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSMSModemInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName4> getSMSModemInfoAsync(Ihc.Soap.Smsmodem.inputMessageName4 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="resetSMSModem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName5> resetSMSModemAsync(Ihc.Soap.Smsmodem.inputMessageName5 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSSMSModemSettings
    {
        
        private string m_powerupMessageField;
        
        private string m_powerdownMessageField;
        
        private string m_powerdownNumberField;
        
        private bool m_relaySMSField;
        
        private bool m_forceStandAloneModeField;
        
        private bool m_sendLowBatteryNotificationField;
        
        private bool m_sendLowBatteryNotificationLanguageField;
        
        private bool m_sendLEDDimmerErrorNotificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string m_powerupMessage
        {
            get
            {
                return this.m_powerupMessageField;
            }
            set
            {
                this.m_powerupMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string m_powerdownMessage
        {
            get
            {
                return this.m_powerdownMessageField;
            }
            set
            {
                this.m_powerdownMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string m_powerdownNumber
        {
            get
            {
                return this.m_powerdownNumberField;
            }
            set
            {
                this.m_powerdownNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool m_relaySMS
        {
            get
            {
                return this.m_relaySMSField;
            }
            set
            {
                this.m_relaySMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool m_forceStandAloneMode
        {
            get
            {
                return this.m_forceStandAloneModeField;
            }
            set
            {
                this.m_forceStandAloneModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool m_sendLowBatteryNotification
        {
            get
            {
                return this.m_sendLowBatteryNotificationField;
            }
            set
            {
                this.m_sendLowBatteryNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool m_sendLowBatteryNotificationLanguage
        {
            get
            {
                return this.m_sendLowBatteryNotificationLanguageField;
            }
            set
            {
                this.m_sendLowBatteryNotificationLanguageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool m_sendLEDDimmerErrorNotification
        {
            get
            {
                return this.m_sendLEDDimmerErrorNotificationField;
            }
            set
            {
                this.m_sendLEDDimmerErrorNotificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSSMSModemInfo
    {
        
        private string firmwareVersionField;
        
        private string gSMChipVersionField;
        
        private string hardwareRevisionField;
        
        private string productionDateField;
        
        private bool detectedField;
        
        private string serialNumberField;
        
        private string iMEINumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string firmwareVersion
        {
            get
            {
                return this.firmwareVersionField;
            }
            set
            {
                this.firmwareVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string gSMChipVersion
        {
            get
            {
                return this.gSMChipVersionField;
            }
            set
            {
                this.gSMChipVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string hardwareRevision
        {
            get
            {
                return this.hardwareRevisionField;
            }
            set
            {
                this.hardwareRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string productionDate
        {
            get
            {
                return this.productionDateField;
            }
            set
            {
                this.productionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool detected
        {
            get
            {
                return this.detectedField;
            }
            set
            {
                this.detectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string serialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string iMEINumber
        {
            get
            {
                return this.iMEINumberField;
            }
            set
            {
                this.iMEINumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSSMSModemStatus
    {
        
        private string antennaCoverageField;
        
        private string mobileOperatorField;
        
        private string modemStatusField;
        
        private string mobileNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string antennaCoverage
        {
            get
            {
                return this.antennaCoverageField;
            }
            set
            {
                this.antennaCoverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mobileOperator
        {
            get
            {
                return this.mobileOperatorField;
            }
            set
            {
                this.mobileOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string modemStatus
        {
            get
            {
                return this.modemStatusField;
            }
            set
            {
                this.modemStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mobileNumber
        {
            get
            {
                return this.mobileNumberField;
            }
            set
            {
                this.mobileNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Smsmodem.WSSMSModemSettings setSMSModemSettings1;
        
        public inputMessageName1()
        {
        }
        
        public inputMessageName1(Ihc.Soap.Smsmodem.WSSMSModemSettings setSMSModemSettings1)
        {
            this.setSMSModemSettings1 = setSMSModemSettings1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName1
    {
        
        public outputMessageName1()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName2
    {
        
        public inputMessageName2()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName2
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Smsmodem.WSSMSModemSettings getSMSModemSettings1;
        
        public outputMessageName2()
        {
        }
        
        public outputMessageName2(Ihc.Soap.Smsmodem.WSSMSModemSettings getSMSModemSettings1)
        {
            this.getSMSModemSettings1 = getSMSModemSettings1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName3
    {
        
        public inputMessageName3()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Smsmodem.WSSMSModemStatus getSMSModemStatus1;
        
        public outputMessageName3()
        {
        }
        
        public outputMessageName3(Ihc.Soap.Smsmodem.WSSMSModemStatus getSMSModemStatus1)
        {
            this.getSMSModemStatus1 = getSMSModemStatus1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName4
    {
        
        public inputMessageName4()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName4
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Smsmodem.WSSMSModemInfo getSMSModemInfo1;
        
        public outputMessageName4()
        {
        }
        
        public outputMessageName4(Ihc.Soap.Smsmodem.WSSMSModemInfo getSMSModemInfo1)
        {
            this.getSMSModemInfo1 = getSMSModemInfo1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName5
    {
        
        public inputMessageName5()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName5
    {
        
        public outputMessageName5()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface SMSModemServiceChannel : Ihc.Soap.Smsmodem.SMSModemService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SMSModemServiceClient : System.ServiceModel.ClientBase<Ihc.Soap.Smsmodem.SMSModemService>, Ihc.Soap.Smsmodem.SMSModemService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SMSModemServiceClient() : 
                base(SMSModemServiceClient.GetDefaultBinding(), SMSModemServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SMSModemServiceBindingPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSModemServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SMSModemServiceClient.GetBindingForEndpoint(endpointConfiguration), SMSModemServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSModemServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SMSModemServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSModemServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SMSModemServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSModemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName1> Ihc.Soap.Smsmodem.SMSModemService.setSMSModemSettingsAsync(Ihc.Soap.Smsmodem.inputMessageName1 request)
        {
            return base.Channel.setSMSModemSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName1> setSMSModemSettingsAsync(Ihc.Soap.Smsmodem.WSSMSModemSettings setSMSModemSettings1)
        {
            Ihc.Soap.Smsmodem.inputMessageName1 inValue = new Ihc.Soap.Smsmodem.inputMessageName1();
            inValue.setSMSModemSettings1 = setSMSModemSettings1;
            return ((Ihc.Soap.Smsmodem.SMSModemService)(this)).setSMSModemSettingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName2> Ihc.Soap.Smsmodem.SMSModemService.getSMSModemSettingsAsync(Ihc.Soap.Smsmodem.inputMessageName2 request)
        {
            return base.Channel.getSMSModemSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName2> getSMSModemSettingsAsync()
        {
            Ihc.Soap.Smsmodem.inputMessageName2 inValue = new Ihc.Soap.Smsmodem.inputMessageName2();
            return ((Ihc.Soap.Smsmodem.SMSModemService)(this)).getSMSModemSettingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName3> Ihc.Soap.Smsmodem.SMSModemService.getSMSModemStatusAsync(Ihc.Soap.Smsmodem.inputMessageName3 request)
        {
            return base.Channel.getSMSModemStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName3> getSMSModemStatusAsync()
        {
            Ihc.Soap.Smsmodem.inputMessageName3 inValue = new Ihc.Soap.Smsmodem.inputMessageName3();
            return ((Ihc.Soap.Smsmodem.SMSModemService)(this)).getSMSModemStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName4> Ihc.Soap.Smsmodem.SMSModemService.getSMSModemInfoAsync(Ihc.Soap.Smsmodem.inputMessageName4 request)
        {
            return base.Channel.getSMSModemInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName4> getSMSModemInfoAsync()
        {
            Ihc.Soap.Smsmodem.inputMessageName4 inValue = new Ihc.Soap.Smsmodem.inputMessageName4();
            return ((Ihc.Soap.Smsmodem.SMSModemService)(this)).getSMSModemInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName5> Ihc.Soap.Smsmodem.SMSModemService.resetSMSModemAsync(Ihc.Soap.Smsmodem.inputMessageName5 request)
        {
            return base.Channel.resetSMSModemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Smsmodem.outputMessageName5> resetSMSModemAsync()
        {
            Ihc.Soap.Smsmodem.inputMessageName5 inValue = new Ihc.Soap.Smsmodem.inputMessageName5();
            return ((Ihc.Soap.Smsmodem.SMSModemService)(this)).resetSMSModemAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SMSModemServiceBindingPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SMSModemServiceBindingPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/SMSModemService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SMSModemServiceClient.GetBindingForEndpoint(EndpointConfiguration.SMSModemServiceBindingPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SMSModemServiceClient.GetEndpointAddress(EndpointConfiguration.SMSModemServiceBindingPort);
        }
        
        public enum EndpointConfiguration
        {
            
            SMSModemServiceBindingPort,
        }
    }
}
