//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ihc.Soap.Testihc
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="utcs", ConfigurationName="Ihc.Soap.Testihc.TestIhcService")]
    public interface TestIhcService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="getAirlinkVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName1> getAirlinkVersionAsync(Ihc.Soap.Testihc.inputMessageName1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getIOBoardVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName2> getIOBoardVersionAsync(Ihc.Soap.Testihc.inputMessageName2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getWiserBoardVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName3> getWiserBoardVersionAsync(Ihc.Soap.Testihc.inputMessageName3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getWiserBoardMACAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName4> getWiserBoardMACAddressAsync(Ihc.Soap.Testihc.inputMessageName4 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getWiserBoardHWVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName5> getWiserBoardHWVersionAsync(Ihc.Soap.Testihc.inputMessageName5 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getWiserBoardSerialNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName6> getWiserBoardSerialNumberAsync(Ihc.Soap.Testihc.inputMessageName6 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sendAirlinkPacket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName7> sendAirlinkPacketAsync(Ihc.Soap.Testihc.inputMessageName7 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="productionTestPassed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName8> productionTestPassedAsync(Ihc.Soap.Testihc.inputMessageName8 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getTimeAndDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName9> getTimeAndDateAsync(Ihc.Soap.Testihc.inputMessageName9 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="setTimeAndDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName10> setTimeAndDateAsync(Ihc.Soap.Testihc.inputMessageName10 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="burnIO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName11> burnIOAsync(Ihc.Soap.Testihc.inputMessageName11 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="testSdCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName12> testSdCardAsync(Ihc.Soap.Testihc.inputMessageName12 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="turnOnRedLed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName13> turnOnRedLedAsync(Ihc.Soap.Testihc.inputMessageName13 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="turnOffRedLed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName14> turnOffRedLedAsync(Ihc.Soap.Testihc.inputMessageName14 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="turnOnGreenLed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName15> turnOnGreenLedAsync(Ihc.Soap.Testihc.inputMessageName15 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="turnOffGreenLed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName16> turnOffGreenLedAsync(Ihc.Soap.Testihc.inputMessageName16 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="turnOnBlueLed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName17> turnOnBlueLedAsync(Ihc.Soap.Testihc.inputMessageName17 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="turnOffBlueLed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName18> turnOffBlueLedAsync(Ihc.Soap.Testihc.inputMessageName18 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="turnOnLeds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName19> turnOnLedsAsync(Ihc.Soap.Testihc.inputMessageName19 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="testIOBoard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName20> testIOBoardAsync(Ihc.Soap.Testihc.inputMessageName20 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="readUsbHost", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName21> readUsbHostAsync(Ihc.Soap.Testihc.inputMessageName21 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sendRS485Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName22> sendRS485DataAsync(Ihc.Soap.Testihc.inputMessageName22 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="readRS485Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName23> readRS485DataAsync(Ihc.Soap.Testihc.inputMessageName23 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName1
    {
        
        public inputMessageName1()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getAirlinkVersion1;
        
        public outputMessageName1()
        {
        }
        
        public outputMessageName1(string getAirlinkVersion1)
        {
            this.getAirlinkVersion1 = getAirlinkVersion1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName2
    {
        
        public inputMessageName2()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName2
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getIOBoardVersion1;
        
        public outputMessageName2()
        {
        }
        
        public outputMessageName2(string getIOBoardVersion1)
        {
            this.getIOBoardVersion1 = getIOBoardVersion1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName3
    {
        
        public inputMessageName3()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getWiserBoardVersion1;
        
        public outputMessageName3()
        {
        }
        
        public outputMessageName3(string getWiserBoardVersion1)
        {
            this.getWiserBoardVersion1 = getWiserBoardVersion1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName4
    {
        
        public inputMessageName4()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName4
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getWiserBoardMACAddress1;
        
        public outputMessageName4()
        {
        }
        
        public outputMessageName4(string getWiserBoardMACAddress1)
        {
            this.getWiserBoardMACAddress1 = getWiserBoardMACAddress1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName5
    {
        
        public inputMessageName5()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName5
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getWiserBoardHWVersion1;
        
        public outputMessageName5()
        {
        }
        
        public outputMessageName5(string getWiserBoardHWVersion1)
        {
            this.getWiserBoardHWVersion1 = getWiserBoardHWVersion1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName6
    {
        
        public inputMessageName6()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName6
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getWiserBoardSerialNumber1;
        
        public outputMessageName6()
        {
        }
        
        public outputMessageName6(string getWiserBoardSerialNumber1)
        {
            this.getWiserBoardSerialNumber1 = getWiserBoardSerialNumber1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName7
    {
        
        public inputMessageName7()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName7
    {
        
        public outputMessageName7()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName8
    {
        
        public inputMessageName8()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName8
    {
        
        public outputMessageName8()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName9
    {
        
        public inputMessageName9()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName9
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> getTimeAndDate1;
        
        public outputMessageName9()
        {
        }
        
        public outputMessageName9(System.Nullable<long> getTimeAndDate1)
        {
            this.getTimeAndDate1 = getTimeAndDate1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName10
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> setTimeAndDate1;
        
        public inputMessageName10()
        {
        }
        
        public inputMessageName10(System.Nullable<long> setTimeAndDate1)
        {
            this.setTimeAndDate1 = setTimeAndDate1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName10
    {
        
        public outputMessageName10()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName11
    {
        
        public inputMessageName11()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName11
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> burnIO1;
        
        public outputMessageName11()
        {
        }
        
        public outputMessageName11(System.Nullable<bool> burnIO1)
        {
            this.burnIO1 = burnIO1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName12
    {
        
        public inputMessageName12()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName12
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> testSdCard1;
        
        public outputMessageName12()
        {
        }
        
        public outputMessageName12(System.Nullable<bool> testSdCard1)
        {
            this.testSdCard1 = testSdCard1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName13
    {
        
        public inputMessageName13()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName13
    {
        
        public outputMessageName13()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName14
    {
        
        public inputMessageName14()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName14
    {
        
        public outputMessageName14()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName15
    {
        
        public inputMessageName15()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName15
    {
        
        public outputMessageName15()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName16
    {
        
        public inputMessageName16()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName16
    {
        
        public outputMessageName16()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName17
    {
        
        public inputMessageName17()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName17
    {
        
        public outputMessageName17()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName18
    {
        
        public inputMessageName18()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName18
    {
        
        public outputMessageName18()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName19
    {
        
        public inputMessageName19()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName19
    {
        
        public outputMessageName19()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName20
    {
        
        public inputMessageName20()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName20
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> testIOBoard1;
        
        public outputMessageName20()
        {
        }
        
        public outputMessageName20(System.Nullable<bool> testIOBoard1)
        {
            this.testIOBoard1 = testIOBoard1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName21
    {
        
        public inputMessageName21()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName21
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> readUsbHost1;
        
        public outputMessageName21()
        {
        }
        
        public outputMessageName21(System.Nullable<bool> readUsbHost1)
        {
            this.readUsbHost1 = readUsbHost1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName22
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sendRS485Data1;
        
        public inputMessageName22()
        {
        }
        
        public inputMessageName22(string sendRS485Data1)
        {
            this.sendRS485Data1 = sendRS485Data1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName22
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> sendRS485Data2;
        
        public outputMessageName22()
        {
        }
        
        public outputMessageName22(System.Nullable<bool> sendRS485Data2)
        {
            this.sendRS485Data2 = sendRS485Data2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName23
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string readRS485Data1;
        
        public inputMessageName23()
        {
        }
        
        public inputMessageName23(string readRS485Data1)
        {
            this.readRS485Data1 = readRS485Data1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName23
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> readRS485Data2;
        
        public outputMessageName23()
        {
        }
        
        public outputMessageName23(System.Nullable<bool> readRS485Data2)
        {
            this.readRS485Data2 = readRS485Data2;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface TestIhcServiceChannel : Ihc.Soap.Testihc.TestIhcService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TestIhcServiceClient : System.ServiceModel.ClientBase<Ihc.Soap.Testihc.TestIhcService>, Ihc.Soap.Testihc.TestIhcService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TestIhcServiceClient() : 
                base(TestIhcServiceClient.GetDefaultBinding(), TestIhcServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TestIhcServiceBindingPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestIhcServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TestIhcServiceClient.GetBindingForEndpoint(endpointConfiguration), TestIhcServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestIhcServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TestIhcServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestIhcServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TestIhcServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestIhcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName1> Ihc.Soap.Testihc.TestIhcService.getAirlinkVersionAsync(Ihc.Soap.Testihc.inputMessageName1 request)
        {
            return base.Channel.getAirlinkVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName1> getAirlinkVersionAsync()
        {
            Ihc.Soap.Testihc.inputMessageName1 inValue = new Ihc.Soap.Testihc.inputMessageName1();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).getAirlinkVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName2> Ihc.Soap.Testihc.TestIhcService.getIOBoardVersionAsync(Ihc.Soap.Testihc.inputMessageName2 request)
        {
            return base.Channel.getIOBoardVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName2> getIOBoardVersionAsync()
        {
            Ihc.Soap.Testihc.inputMessageName2 inValue = new Ihc.Soap.Testihc.inputMessageName2();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).getIOBoardVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName3> Ihc.Soap.Testihc.TestIhcService.getWiserBoardVersionAsync(Ihc.Soap.Testihc.inputMessageName3 request)
        {
            return base.Channel.getWiserBoardVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName3> getWiserBoardVersionAsync()
        {
            Ihc.Soap.Testihc.inputMessageName3 inValue = new Ihc.Soap.Testihc.inputMessageName3();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).getWiserBoardVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName4> Ihc.Soap.Testihc.TestIhcService.getWiserBoardMACAddressAsync(Ihc.Soap.Testihc.inputMessageName4 request)
        {
            return base.Channel.getWiserBoardMACAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName4> getWiserBoardMACAddressAsync()
        {
            Ihc.Soap.Testihc.inputMessageName4 inValue = new Ihc.Soap.Testihc.inputMessageName4();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).getWiserBoardMACAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName5> Ihc.Soap.Testihc.TestIhcService.getWiserBoardHWVersionAsync(Ihc.Soap.Testihc.inputMessageName5 request)
        {
            return base.Channel.getWiserBoardHWVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName5> getWiserBoardHWVersionAsync()
        {
            Ihc.Soap.Testihc.inputMessageName5 inValue = new Ihc.Soap.Testihc.inputMessageName5();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).getWiserBoardHWVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName6> Ihc.Soap.Testihc.TestIhcService.getWiserBoardSerialNumberAsync(Ihc.Soap.Testihc.inputMessageName6 request)
        {
            return base.Channel.getWiserBoardSerialNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName6> getWiserBoardSerialNumberAsync()
        {
            Ihc.Soap.Testihc.inputMessageName6 inValue = new Ihc.Soap.Testihc.inputMessageName6();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).getWiserBoardSerialNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName7> Ihc.Soap.Testihc.TestIhcService.sendAirlinkPacketAsync(Ihc.Soap.Testihc.inputMessageName7 request)
        {
            return base.Channel.sendAirlinkPacketAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName7> sendAirlinkPacketAsync()
        {
            Ihc.Soap.Testihc.inputMessageName7 inValue = new Ihc.Soap.Testihc.inputMessageName7();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).sendAirlinkPacketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName8> Ihc.Soap.Testihc.TestIhcService.productionTestPassedAsync(Ihc.Soap.Testihc.inputMessageName8 request)
        {
            return base.Channel.productionTestPassedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName8> productionTestPassedAsync()
        {
            Ihc.Soap.Testihc.inputMessageName8 inValue = new Ihc.Soap.Testihc.inputMessageName8();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).productionTestPassedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName9> Ihc.Soap.Testihc.TestIhcService.getTimeAndDateAsync(Ihc.Soap.Testihc.inputMessageName9 request)
        {
            return base.Channel.getTimeAndDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName9> getTimeAndDateAsync()
        {
            Ihc.Soap.Testihc.inputMessageName9 inValue = new Ihc.Soap.Testihc.inputMessageName9();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).getTimeAndDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName10> Ihc.Soap.Testihc.TestIhcService.setTimeAndDateAsync(Ihc.Soap.Testihc.inputMessageName10 request)
        {
            return base.Channel.setTimeAndDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName10> setTimeAndDateAsync(System.Nullable<long> setTimeAndDate1)
        {
            Ihc.Soap.Testihc.inputMessageName10 inValue = new Ihc.Soap.Testihc.inputMessageName10();
            inValue.setTimeAndDate1 = setTimeAndDate1;
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).setTimeAndDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName11> Ihc.Soap.Testihc.TestIhcService.burnIOAsync(Ihc.Soap.Testihc.inputMessageName11 request)
        {
            return base.Channel.burnIOAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName11> burnIOAsync()
        {
            Ihc.Soap.Testihc.inputMessageName11 inValue = new Ihc.Soap.Testihc.inputMessageName11();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).burnIOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName12> Ihc.Soap.Testihc.TestIhcService.testSdCardAsync(Ihc.Soap.Testihc.inputMessageName12 request)
        {
            return base.Channel.testSdCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName12> testSdCardAsync()
        {
            Ihc.Soap.Testihc.inputMessageName12 inValue = new Ihc.Soap.Testihc.inputMessageName12();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).testSdCardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName13> Ihc.Soap.Testihc.TestIhcService.turnOnRedLedAsync(Ihc.Soap.Testihc.inputMessageName13 request)
        {
            return base.Channel.turnOnRedLedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName13> turnOnRedLedAsync()
        {
            Ihc.Soap.Testihc.inputMessageName13 inValue = new Ihc.Soap.Testihc.inputMessageName13();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).turnOnRedLedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName14> Ihc.Soap.Testihc.TestIhcService.turnOffRedLedAsync(Ihc.Soap.Testihc.inputMessageName14 request)
        {
            return base.Channel.turnOffRedLedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName14> turnOffRedLedAsync()
        {
            Ihc.Soap.Testihc.inputMessageName14 inValue = new Ihc.Soap.Testihc.inputMessageName14();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).turnOffRedLedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName15> Ihc.Soap.Testihc.TestIhcService.turnOnGreenLedAsync(Ihc.Soap.Testihc.inputMessageName15 request)
        {
            return base.Channel.turnOnGreenLedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName15> turnOnGreenLedAsync()
        {
            Ihc.Soap.Testihc.inputMessageName15 inValue = new Ihc.Soap.Testihc.inputMessageName15();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).turnOnGreenLedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName16> Ihc.Soap.Testihc.TestIhcService.turnOffGreenLedAsync(Ihc.Soap.Testihc.inputMessageName16 request)
        {
            return base.Channel.turnOffGreenLedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName16> turnOffGreenLedAsync()
        {
            Ihc.Soap.Testihc.inputMessageName16 inValue = new Ihc.Soap.Testihc.inputMessageName16();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).turnOffGreenLedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName17> Ihc.Soap.Testihc.TestIhcService.turnOnBlueLedAsync(Ihc.Soap.Testihc.inputMessageName17 request)
        {
            return base.Channel.turnOnBlueLedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName17> turnOnBlueLedAsync()
        {
            Ihc.Soap.Testihc.inputMessageName17 inValue = new Ihc.Soap.Testihc.inputMessageName17();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).turnOnBlueLedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName18> Ihc.Soap.Testihc.TestIhcService.turnOffBlueLedAsync(Ihc.Soap.Testihc.inputMessageName18 request)
        {
            return base.Channel.turnOffBlueLedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName18> turnOffBlueLedAsync()
        {
            Ihc.Soap.Testihc.inputMessageName18 inValue = new Ihc.Soap.Testihc.inputMessageName18();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).turnOffBlueLedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName19> Ihc.Soap.Testihc.TestIhcService.turnOnLedsAsync(Ihc.Soap.Testihc.inputMessageName19 request)
        {
            return base.Channel.turnOnLedsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName19> turnOnLedsAsync()
        {
            Ihc.Soap.Testihc.inputMessageName19 inValue = new Ihc.Soap.Testihc.inputMessageName19();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).turnOnLedsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName20> Ihc.Soap.Testihc.TestIhcService.testIOBoardAsync(Ihc.Soap.Testihc.inputMessageName20 request)
        {
            return base.Channel.testIOBoardAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName20> testIOBoardAsync()
        {
            Ihc.Soap.Testihc.inputMessageName20 inValue = new Ihc.Soap.Testihc.inputMessageName20();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).testIOBoardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName21> Ihc.Soap.Testihc.TestIhcService.readUsbHostAsync(Ihc.Soap.Testihc.inputMessageName21 request)
        {
            return base.Channel.readUsbHostAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName21> readUsbHostAsync()
        {
            Ihc.Soap.Testihc.inputMessageName21 inValue = new Ihc.Soap.Testihc.inputMessageName21();
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).readUsbHostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName22> Ihc.Soap.Testihc.TestIhcService.sendRS485DataAsync(Ihc.Soap.Testihc.inputMessageName22 request)
        {
            return base.Channel.sendRS485DataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName22> sendRS485DataAsync(string sendRS485Data1)
        {
            Ihc.Soap.Testihc.inputMessageName22 inValue = new Ihc.Soap.Testihc.inputMessageName22();
            inValue.sendRS485Data1 = sendRS485Data1;
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).sendRS485DataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName23> Ihc.Soap.Testihc.TestIhcService.readRS485DataAsync(Ihc.Soap.Testihc.inputMessageName23 request)
        {
            return base.Channel.readRS485DataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Testihc.outputMessageName23> readRS485DataAsync(string readRS485Data1)
        {
            Ihc.Soap.Testihc.inputMessageName23 inValue = new Ihc.Soap.Testihc.inputMessageName23();
            inValue.readRS485Data1 = readRS485Data1;
            return ((Ihc.Soap.Testihc.TestIhcService)(this)).readRS485DataAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TestIhcServiceBindingPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TestIhcServiceBindingPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/TestIhcService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TestIhcServiceClient.GetBindingForEndpoint(EndpointConfiguration.TestIhcServiceBindingPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TestIhcServiceClient.GetEndpointAddress(EndpointConfiguration.TestIhcServiceBindingPort);
        }
        
        public enum EndpointConfiguration
        {
            
            TestIhcServiceBindingPort,
        }
    }
}
