<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <CopyDebugSymbolFilesFromPackages>true</CopyDebugSymbolFilesFromPackages>
    <Version>0.9.0</Version>
    <InformationalVersion>This is a beta version</InformationalVersion>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <Copyright>Apache License 2.0</Copyright>
    <Authors>mmc41</Authors>
    <AssemblyTitle>IHC Lab</AssemblyTitle>
    <Product>IHC Lab</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FakeItEasy" />
    <ProjectReference Include="..\..\ihcclient\ihcclient.csproj" />
    <ProjectReference Include="..\..\shared\ihc_appbootstrap\ihc_appbootstrap.csproj" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Simple" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <Target Name="CopyConfigFiles" AfterTargets="AfterBuild">
    <!-- NB: Settings file is required for running/testing but allow build without the file to support compilation in a DevOps pipeline -->
    <Copy SourceFiles="..\..\ihcsettings.json" DestinationFolder="$(OutDir)" Condition="Exists('..\..\ihcsettings.json')" />
  </Target>
  <Target Name="DeleteConfigFiles" AfterTargets="Clean">
    <!-- Delete ihcsettings.json from output directory during clean -->
    <Delete Files="$(OutDir)ihcsettings.json" Condition="Exists('$(OutDir)ihcsettings.json')" />
  </Target>
</Project>
