using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using ihc_openvisual.Services;

namespace ihc_openvisual.ViewModels;

/// <summary>
/// Backs the <i>Rediger data tabeller</i> dialog (US-049): the eighteen data tables on the left, the selected
/// table's user-defined texts on the right, with Tilføj / Rediger / Slet over those texts.
///
/// <para>
/// Edits land in a WORKING COPY and reach <see cref="DataTableStore"/> only on <see cref="Commit"/> — the vendor's
/// dialog has OK and Annuller, so an installer who deletes a text and then cancels must get it back. That is also
/// why <i>Slet</i> needs no confirmation prompt here even though it asks for none in the vendor either: Annuller
/// is the undo.
/// </para>
/// <para>
/// Avalonia-free so it is headlessly testable; the window is a thin view over it.
/// </para>
/// </summary>
public partial class DataTablesViewModel : ViewModelBase, IDataTablesDialogViewModel
{
    private readonly DataTableStore _store;
    private readonly IDialogService _dialogs;

    // The working copy: every table's texts, keyed as the store keys them. Seeded from the store on construction.
    private readonly Dictionary<string, List<string>> _working;

    public ObservableCollection<DataTableDefinition> Tables { get; } = new();

    /// <summary>The selected table's texts. Rebuilt on every table change, so the right list always belongs to
    /// the left list's selection.</summary>
    public ObservableCollection<string> Texts { get; } = new();

    [ObservableProperty] private DataTableDefinition? _selectedTable;
    [ObservableProperty] private string? _selectedText;

    public DataTablesViewModel(DataTableStore store, IDialogService dialogs)
    {
        _store = store;
        _dialogs = dialogs;
        _working = DataTableStore.Definitions.ToDictionary(
            d => d.Key, d => store.TextsFor(d.Key).ToList(), System.StringComparer.Ordinal);

        foreach (DataTableDefinition table in DataTableStore.Definitions)
            Tables.Add(table);
        SelectedTable = Tables.FirstOrDefault();   // the vendor opens with the first table selected
    }

    // Generated by [ObservableProperty]: the right list follows the left list's selection.
    partial void OnSelectedTableChanged(DataTableDefinition? value) => ReloadTexts();

    /// <summary>Writes the working copy to the store — the dialog's OK.</summary>
    public void Commit() =>
        _store.Commit(_working.ToDictionary(p => p.Key, p => (IReadOnlyList<string>)p.Value, System.StringComparer.Ordinal));

    [RelayCommand]
    private async Task AddText()
    {
        if (Current is not { } texts)
            return;
        PropertiesResult? result = await _dialogs.EditPropertiesAsync("Ny tekst", string.Empty, string.Empty);
        if (result is null || string.IsNullOrWhiteSpace(result.Name))
            return;
        texts.Add(result.Name.Trim());
        ReloadTexts();
        SelectedText = texts[^1];
    }

    [RelayCommand]
    private async Task EditText()
    {
        if (Current is not { } texts || SelectedText is not { } selected)
            return;
        int index = texts.IndexOf(selected);
        if (index < 0)
            return;
        PropertiesResult? result = await _dialogs.EditPropertiesAsync("Rediger tekst", selected, string.Empty);
        if (result is null || string.IsNullOrWhiteSpace(result.Name))
            return;
        texts[index] = result.Name.Trim();
        ReloadTexts();
        SelectedText = texts[index];
    }

    /// <summary>The vendor deletes with no confirmation prompt (US-049) — safe here because the deletion lives in
    /// the working copy until OK, so Annuller restores it.</summary>
    [RelayCommand]
    private void DeleteText()
    {
        if (Current is not { } texts || SelectedText is not { } selected)
            return;
        texts.Remove(selected);
        ReloadTexts();
    }

    /// <summary>Rediger and Slet are greyed until a text row is picked — the vendor's own enablement, read off its
    /// dialog (they stayed greyed with seven texts listed and none selected).
    /// <para>
    /// A bound <c>IsEnabled</c>, not <c>[RelayCommand(CanExecute)]</c>: command availability has exactly one home in
    /// this app — the registry row's Gate — and an architecture test bans a second, competing predicate. These two
    /// buttons are dialog-local and have no registry row, so the enablement is a view-model property the view binds.
    /// </para>
    /// </summary>
    public bool HasSelectedText => SelectedText is not null;

    partial void OnSelectedTextChanged(string? value) => OnPropertyChanged(nameof(HasSelectedText));

    private List<string>? Current =>
        SelectedTable is { } table && _working.TryGetValue(table.Key, out List<string>? texts) ? texts : null;

    private void ReloadTexts()
    {
        Texts.Clear();
        foreach (string text in Current ?? [])
            Texts.Add(text);
        SelectedText = null;
    }
}
